---
title: "HR MCP"
author: "Justine Lang"
date: "2024-01-24"
output: 
  html_document: 
    code_folding: show
---

```{r setup, echo = TRUE, warning = FALSE, message = FALSE, results = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, results = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(adehabitatHR)
library(sp)
library(scales)
library(ggmap)
```

```{r}
# Read the csv file
turtles <- read_csv(here("Habitat_Portfolio", "other_data","tracking_sample.csv"))
```

```{r}
# SpatialPointsDataFrame objects don't like missing values
# Remove two rows with NA's
turtles <- turtles[!is.na(turtles$x) & !is.na(turtles$y),]

# Only include three columns (id, x, and y coordinates) for making MCP's
turtles.sp <- turtles[, c("id", "x", "y")] 

# Create a SpatialPointsDataFrame by defining the coordinates
coordinates(turtles.sp) <- c("x", "y")

# Set the coordinate reference system (CRS)
# More information on CRS here: 
# https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/OverviewCoordinateReferenceSystems.pdf
# The sample data are UTM points in WGS84 from zone 18N
proj4string(turtles.sp) <- CRS( "+proj=utm +zone=18 +datum=WGS84 +units=m +no_defs" )
```

```{r}
# Calculate MCPs for each turtle
turtles.mcp <- mcp(turtles.sp, percent = 100)

# Examine output
turtles.mcp
```

```{r}
# Plot
# library(scales) # Helps make polygons partly transparent using the alpha argument below
plot(turtles.sp, col = as.factor(turtles.sp@data$id), pch = 16)
plot(turtles.mcp, col = alpha(1:5, 0.5), add = TRUE)
```

```{r}
# Calculate the MCP by including 50 to 100 percent of points
hrs <- mcp.area(turtles.sp, percent = seq(50, 100, by = 5))
```

```{r}
hrs # examine dataframe
```

```{r}
# Transform the point and MCP objects. 
turtles.spgeo <- spTransform(turtles.sp, CRS("+proj=longlat"))
turtles.mcpgeo <- spTransform(turtles.mcp, CRS("+proj=longlat"))

# Download tiles using ggmap
# Google tiles (requires a key first)
## Guide on getting a key: https://www.r-bloggers.com/geocoding-with-ggmap-and-the-google-api/
# register_google(key = "mykeyhere")
# mybasemap <- get_map(location = c(lon = mean(turtles.spgeo@coords[,1]), 
#                                   lat = mean(turtles.spgeo@coords[,2])), 
#                      source = "google", 
#                      zoom = 14,
#                     maptype = 'satellite')

register_stadiamaps(key = "abd38f6a-07a9-43fb-99fa-9288b2fdb209")

mybasemap <- get_stadiamap(bbox = c(left = min(turtles.spgeo@coords[,1])-0.005, 
                                    bottom = min(turtles.spgeo@coords[,2])-0.005, 
                                    right = max(turtles.spgeo@coords[,1])+0.005, 
                                    top = max(turtles.spgeo@coords[,2])+0.005), 
                           zoom = 12)

# Turn the spatial data frame of points into just a dataframe for plotting in ggmap
turtles.geo <- data.frame(turtles.spgeo@coords, 
                          id = turtles.spgeo@data$id )

mymap.hr <- ggmap(mybasemap) + 
  geom_polygon(data = fortify(turtles.mcpgeo),  
               # Polygon layer needs to be "fortified" to add geometry to the dataframe
              aes(long, lat, colour = id, fill = id),
              alpha = 0.3) + # alpha sets the transparency
  geom_point(data = turtles.geo, 
             aes(x = x, y = y, colour = id))  +
  theme(legend.position = c(0.15, 0.80)) +
  labs(x = "Longitude", y = "Latitude") +
  scale_fill_manual(name = "Turtle number", 
                      values = c("red", "blue", "purple", "green", "orange"),
                      breaks = c("T001", "T002", "T003", "T004", "T005")) +
  scale_colour_manual(name = "Turtle number", 
                      values = c("red", "blue", "purple", "green", "orange"),
                      breaks = c("T001", "T002", "T003", "T004", "T005"))
mymap.hr
```





